config/routes.rb
TrainerFinder::Application.routes.draw do
  get "trainers/getTrainers"
  resources :trainers

  root :to => "trainers#new"

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :phone
  validates_presence_of :bio
  validates_presence_of :citiesServed
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "must be valid"
  validates_length_of :name, :maximum => 255
  validates_length_of :priceRange, :maximum => 255
  validates_length_of :phone, :maximum => 255
  validates_length_of :citiesServed, :maximum => 255 
  validates_length_of :certs, :maximum => 255 
  validates_length_of :education, :maximum => 255 
  validates_length_of :specialty, :maximum => 255 
  validates_length_of :bio, :maximum => 255
  validates_length_of :philos, :maximum => 255 
  validates_numericality_of :rating, :only_integer => true, :message => "can only be whole number.", :allow_nil => true
  validates_numericality_of :lat, :only_integer => false, :message => "can only be float", :allow_nil => true
  validates_numericality_of :lon, :only_integer => false, :message => "can only be float", :allow_nil => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  # GET /trainers
  # GET /trainers.xml
  def index
    @trainers = Trainer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trainers }
    end
  end

  # GET /trainers/1
  # GET /trainers/1.xml
  def show
    @trainer = Trainer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trainer }
    end
  end

  # GET /trainers/new
  # GET /trainers/new.xml
  def new
    @trainer = Trainer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trainer }
    end
  end

  # GET /trainers/1/edit
  def edit
    @trainer = Trainer.find(params[:id])
  end

  # POST /trainers
  # POST /trainers.xml
  def create
    @trainer = Trainer.new(params[:trainer])

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to(@trainer, :notice => 'Trainer was successfully created.') }
        format.xml  { render :xml => @trainer, :status => :created, :location => @trainer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trainer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trainers/1
  # PUT /trainers/1.xml
  def update
    @trainer = Trainer.find(params[:id])

    respond_to do |format|
      if @trainer.update_attributes(params[:trainer])
        format.html { redirect_to(@trainer, :notice => 'Trainer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trainer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.xml
  def destroy
    @trainer = Trainer.find(params[:id])
    @trainer.destroy

    respond_to do |format|
      format.html { redirect_to(trainers_url) }
      format.xml  { head :ok }
    end
  end
  def getTrainers
    @trainers = Trainer.all
    render :json => @trainers.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrainerFinder</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% @trainer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :'Price Range' %><br />
    <%= f.text_field :priceRange %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :'Cities Served' %><br />
    <%= f.text_field :citiesServed %>
  </div>
  <div class="field">
    <%= f.label :certs %><br />
    <%= f.text_field :certs %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :philos %><br />
    <%= f.text_field :philos %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<h1>Listing trainers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Pricerange</th>
    <th>Phone</th>
    <th>Citiesserved</th>
    <th>Certs</th>
    <th>Education</th>
    <th>Specialty</th>
    <th>Bio</th>
    <th>Philos</th>
    <th>Rating</th>
    <th>Lat</th>
    <th>Lon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trainers.each do |trainer| %>
  <tr>
    <td><%= trainer.name %></td>
    <td><%= trainer.email %></td>
    <td><%= trainer.priceRange %></td>
    <td><%= trainer.phone %></td>
    <td><%= trainer.citiesServed %></td>
    <td><%= trainer.certs %></td>
    <td><%= trainer.education %></td>
    <td><%= trainer.specialty %></td>
    <td><%= trainer.bio %></td>
    <td><%= trainer.philos %></td>
    <td><%= trainer.rating %></td>
    <td><%= trainer.lat %></td>
    <td><%= trainer.lon %></td>
    <td><%= link_to 'Show', trainer %></td>
    <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
    <td><%= link_to 'Destroy', trainer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @trainer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @trainer.email %>
</p>

<p>
  <b>Pricerange:</b>
  <%= @trainer.priceRange %>
</p>

<p>
  <b>Phone:</b>
  <%= @trainer.phone %>
</p>

<p>
  <b>Citiesserved:</b>
  <%= @trainer.citiesServed %>
</p>

<p>
  <b>Certs:</b>
  <%= @trainer.certs %>
</p>

<p>
  <b>Education:</b>
  <%= @trainer.education %>
</p>

<p>
  <b>Specialty:</b>
  <%= @trainer.specialty %>
</p>

<p>
  <b>Bio:</b>
  <%= @trainer.bio %>
</p>

<p>
  <b>Philos:</b>
  <%= @trainer.philos %>
</p>

<p>
  <b>Rating:</b>
  <%= @trainer.rating %>
</p>

<p>
  <b>Lat:</b>
  <%= @trainer.lat %>
</p>

<p>
  <b>Lon:</b>
  <%= @trainer.lon %>
</p>